FROM keithmcclellan/miniconda3:ubuntu-cuda9.1-cudnn7

MAINTAINER Vishnu Mohan <vishnu@mesosphere.com>

COPY --chown="1000:100" beakerx-conda-env.yml "${HOME}/work/"

RUN mkdir -p $HOME/.sparkmagic \
    && ${CONDA_DIR}/bin/conda env create --json -q -f beakerx-conda-env.yml \
    && ${CONDA_DIR}/bin/conda clean --json -tipsy \
    && bash -c 'source activate beakerx \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager \
    && jupyter labextension install @jupyterlab/hub-extension \
    && jupyter labextension install @jupyterlab/geojson-extension \
    && jupyter labextension install @jupyterlab/github \
    && jupyter labextension install jupyterlab_bokeh \
    && jupyter labextension install beakerx-jupyterlab \
    && source deactivate'

RUN bash -c 'source activate beakerx && conda install jupyterhub && source deactivate'

EXPOSE 8888
CMD ["notebook.sh"]

COPY --chown="1000:100" jupyter_notebook_config.py "${HOME}/.jupyter/"
COPY notebook.sh /usr/local/bin/
